/** Items for the equation dialog: `insert` is pasted into the LaTeX field. */
export type MathPaletteItem = {
  insert: string;
  /** Shown on the button (often Unicode or a short name). */
  label: string;
  /** Accessible / tooltip — full LaTeX command when label is abbreviated. */
  title?: string;
  /** If set, caret is placed this many characters from the start of `insert` (0-based). */
  cursorInInsert?: number;
};

export type MathPaletteTab = {
  id: string;
  label: string;
  items: MathPaletteItem[];
};

export const MATH_SYMBOL_PALETTE: MathPaletteTab[] = [
  {
    id: "common",
    label: "Common",
    items: [
      { insert: "+", label: "+" },
      { insert: "-", label: "−", title: "minus" },
      { insert: "\\pm", label: "±" },
      { insert: "\\mp", label: "∓" },
      { insert: "\\times", label: "×" },
      { insert: "\\div", label: "÷" },
      { insert: "\\cdot", label: "·" },
      { insert: "=", label: "=" },
      { insert: "\\neq", label: "≠" },
      { insert: "\\approx", label: "≈" },
      { insert: "\\equiv", label: "≡" },
      { insert: "<", label: "<" },
      { insert: ">", label: ">" },
      { insert: "\\leq", label: "≤" },
      { insert: "\\geq", label: "≥" },
      { insert: "\\ll", label: "≪" },
      { insert: "\\gg", label: "≫" },
      { insert: "\\infty", label: "∞" },
      { insert: "\\partial", label: "∂" },
      { insert: "\\nabla", label: "∇" },
      { insert: "'", label: "′", title: "prime" },
      { insert: "\\prime", label: "prime" },
      { insert: "\\ldots", label: "…" },
      { insert: "\\cdots", label: "⋯" },
    ],
  },
  {
    id: "greek-lower",
    label: "Greek",
    items: [
      { insert: "\\alpha", label: "α" },
      { insert: "\\beta", label: "β" },
      { insert: "\\gamma", label: "γ" },
      { insert: "\\delta", label: "δ" },
      { insert: "\\epsilon", label: "ε" },
      { insert: "\\varepsilon", label: "ε" },
      { insert: "\\zeta", label: "ζ" },
      { insert: "\\eta", label: "η" },
      { insert: "\\theta", label: "θ" },
      { insert: "\\vartheta", label: "ϑ" },
      { insert: "\\iota", label: "ι" },
      { insert: "\\kappa", label: "κ" },
      { insert: "\\lambda", label: "λ" },
      { insert: "\\mu", label: "μ" },
      { insert: "\\nu", label: "ν" },
      { insert: "\\xi", label: "ξ" },
      { insert: "\\pi", label: "π" },
      { insert: "\\rho", label: "ρ" },
      { insert: "\\sigma", label: "σ" },
      { insert: "\\varsigma", label: "ς" },
      { insert: "\\tau", label: "τ" },
      { insert: "\\upsilon", label: "υ" },
      { insert: "\\phi", label: "φ" },
      { insert: "\\varphi", label: "φ" },
      { insert: "\\chi", label: "χ" },
      { insert: "\\psi", label: "ψ" },
      { insert: "\\omega", label: "ω" },
    ],
  },
  {
    id: "greek-upper",
    label: "Γ–Ω",
    items: [
      { insert: "\\Gamma", label: "Γ" },
      { insert: "\\Delta", label: "Δ" },
      { insert: "\\Theta", label: "Θ" },
      { insert: "\\Lambda", label: "Λ" },
      { insert: "\\Xi", label: "Ξ" },
      { insert: "\\Pi", label: "Π" },
      { insert: "\\Sigma", label: "Σ" },
      { insert: "\\Upsilon", label: "Υ" },
      { insert: "\\Phi", label: "Φ" },
      { insert: "\\Psi", label: "Ψ" },
      { insert: "\\Omega", label: "Ω" },
    ],
  },
  {
    id: "calculus",
    label: "Calc",
    items: [
      { insert: "\\sum", label: "Σ", title: "\\sum" },
      { insert: "\\prod", label: "Π", title: "\\prod" },
      { insert: "\\int", label: "∫" },
      { insert: "\\iint", label: "∬" },
      { insert: "\\iiint", label: "∭" },
      { insert: "\\oint", label: "∮" },
      { insert: "\\lim", label: "lim" },
      { insert: "\\limsup", label: "lim sup" },
      { insert: "\\liminf", label: "lim inf" },
      { insert: "\\max", label: "max" },
      { insert: "\\min", label: "min" },
      { insert: "\\sup", label: "sup" },
      { insert: "\\inf", label: "inf" },
      { insert: "\\arg", label: "arg" },
      { insert: "\\deg", label: "deg" },
      { insert: "\\det", label: "det" },
      { insert: "\\dim", label: "dim" },
      { insert: "\\gcd", label: "gcd" },
      { insert: "\\hom", label: "hom" },
      { insert: "\\ker", label: "ker" },
    ],
  },
  {
    id: "arrows",
    label: "Arrows",
    items: [
      { insert: "\\rightarrow", label: "→" },
      { insert: "\\Rightarrow", label: "⇒" },
      { insert: "\\leftarrow", label: "←" },
      { insert: "\\Leftarrow", label: "⇐" },
      { insert: "\\leftrightarrow", label: "↔" },
      { insert: "\\Leftrightarrow", label: "⇔" },
      { insert: "\\mapsto", label: "↦" },
      { insert: "\\to", label: "→", title: "\\to" },
      { insert: "\\gets", label: "←", title: "\\gets" },
      { insert: "\\uparrow", label: "↑" },
      { insert: "\\downarrow", label: "↓" },
      { insert: "\\nearrow", label: "↗" },
      { insert: "\\searrow", label: "↘" },
      { insert: "\\hookrightarrow", label: "↪" },
      { insert: "\\longrightarrow", label: "⟶" },
    ],
  },
  {
    id: "sets",
    label: "Sets",
    items: [
      { insert: "\\in", label: "∈" },
      { insert: "\\notin", label: "∉" },
      { insert: "\\subset", label: "⊂" },
      { insert: "\\supset", label: "⊃" },
      { insert: "\\subseteq", label: "⊆" },
      { insert: "\\supseteq", label: "⊇" },
      { insert: "\\subsetneq", label: "⊊" },
      { insert: "\\cup", label: "∪" },
      { insert: "\\cap", label: "∩" },
      { insert: "\\setminus", label: "∖" },
      { insert: "\\emptyset", label: "∅" },
      { insert: "\\varnothing", label: "∅" },
      { insert: "\\forall", label: "∀" },
      { insert: "\\exists", label: "∃" },
      { insert: "\\nexists", label: "∄" },
      { insert: "\\neg", label: "¬" },
      { insert: "\\land", label: "∧" },
      { insert: "\\lor", label: "∨" },
      { insert: "\\oplus", label: "⊕" },
      { insert: "\\otimes", label: "⊗" },
    ],
  },
  {
    id: "templates",
    label: "Templates",
    items: [
      {
        insert: "\\frac{}{}",
        label: "a/b",
        title: "Fraction \\frac{}{}",
        cursorInInsert: 6,
      },
      {
        insert: "\\sqrt{}",
        label: "√",
        title: "Square root",
        cursorInInsert: 6,
      },
      {
        insert: "\\sqrt[]{}",
        label: "ⁿ√",
        title: "nth root",
        cursorInInsert: 7,
      },
      {
        insert: "^{}",
        label: "xⁿ",
        title: "Superscript",
        cursorInInsert: 2,
      },
      {
        insert: "_{}",
        label: "xₙ",
        title: "Subscript",
        cursorInInsert: 2,
      },
      {
        insert: "\\int_{}^{}",
        label: "∫ₐᵇ",
        title: "Integral with bounds",
        cursorInInsert: 6,
      },
      {
        insert: "\\sum_{}^{}",
        label: "Σ",
        title: "Sum with bounds",
        cursorInInsert: 6,
      },
      {
        insert: "\\lim_{}",
        label: "lim",
        title: "Limit",
        cursorInInsert: 6,
      },
      {
        insert: "\\begin{pmatrix} \\end{pmatrix}",
        label: "matrix",
        title: "pmatrix",
        cursorInInsert: 16,
      },
      {
        insert: "\\begin{bmatrix} \\end{bmatrix}",
        label: "bmatrix",
        title: "bmatrix",
        cursorInInsert: 16,
      },
      {
        insert: "\\left( \\right)",
        label: "(·)",
        title: "\\left( \\right)",
        cursorInInsert: 6,
      },
      {
        insert: "\\left[ \\right]",
        label: "[·]",
        title: "\\left[ \\right]",
        cursorInInsert: 6,
      },
      {
        insert: "\\left\\{ \\right\\}",
        label: "{·}",
        title: "\\left\\{ \\right\\}",
        cursorInInsert: 7,
      },
    ],
  },
  {
    id: "functions",
    label: "Fns",
    items: [
      { insert: "\\sin", label: "sin" },
      { insert: "\\cos", label: "cos" },
      { insert: "\\tan", label: "tan" },
      { insert: "\\cot", label: "cot" },
      { insert: "\\sec", label: "sec" },
      { insert: "\\csc", label: "csc" },
      { insert: "\\arcsin", label: "arcsin" },
      { insert: "\\arccos", label: "arccos" },
      { insert: "\\arctan", label: "arctan" },
      { insert: "\\sinh", label: "sinh" },
      { insert: "\\cosh", label: "cosh" },
      { insert: "\\tanh", label: "tanh" },
      { insert: "\\log", label: "log" },
      { insert: "\\ln", label: "ln" },
      { insert: "\\lg", label: "lg" },
      { insert: "\\exp", label: "exp" },
    ],
  },
];
